/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package ProjectCN;

/**
 *
 * @author Dell
 */
import java.util.HashMap;
import ProjectCN.MainClient;
import java.net.Socket;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    static HashMap<String,String[]> globalmap=new HashMap<String,String[]>();
    int size,queno=1;
    int mark=0;
    String correctans;
    public Client() throws Exception
    {
        initComponents();
        jButton2.setEnabled(false);
       sample(Integer.toString(queno));
          
    }
    public Client(HashMap<String,String[]> hm)
    {   globalmap=hm;
        display();    
    }
    public void sample(String n)throws Exception
    { 
        size=globalmap.size();
        int i=0;
        String str[]=new String[6];
        for (String s:globalmap.get(n))
        {
            str[i]=s;
            System.out.println(str[i]);
            i++;
        }
       qno.setText(n);
       questiontxt.setText(str[0]);
       op1.setText(str[1]);
       op2.setText(str[2]);
       op3.setText(str[3]);
       op4.setText(str[4]);
       correctans=str[5];
       
    }
    
    public void answerCheck()throws Exception
    {
        
        String answerAnswer="";
        if(op1.isSelected())
        {
            answerAnswer=op1.getText();
        }
        else if(op2.isSelected())
        {
            answerAnswer=op2.getText();
        }
        else if(op3.isSelected())
        {
            answerAnswer=op3.getText();
        }
        else if(op4.isSelected())
        {
            answerAnswer=op4.getText();
        }
        else if(answerAnswer=="")
        {
            //JOptionPane.showMessageDialog(this,"Question not answered");
            //nextbutton.setEnabled(false);
            
        }
        if(answerAnswer.equals(correctans))
        {
            mark++;
        }
        buttonGroup1.clearSelection();
        System.out.println("Answer selected :"+answerAnswer);
        System.out.println(mark);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qno = new javax.swing.JLabel();
        questiontxt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JRadioButton();
        nextbutton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("QUESTIONS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 11, -1, -1));

      qno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qno.setText("Number");
        getContentPane().add(qno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, -1, -1));

        questiontxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        questiontxt.setText("jLabel3");
        getContentPane().add(questiontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 812, -1));

        buttonGroup1.add(op1);
        op1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        op1.setText("option1");

        buttonGroup1.add(op2);
        op2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        op2.setText("jRadioButton2");

        buttonGroup1.add(op3);
        op3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        op3.setText("jRadioButton3");

        buttonGroup1.add(op4);
        op4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        op4.setText("jRadioButton4");
       
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(op4, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(op3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addComponent(op1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(op2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(617, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(op1)
                .addGap(18, 18, 18)
                .addComponent(op2)
                .addGap(18, 18, 18)
                .addComponent(op3)
                .addGap(18, 18, 18)
                .addComponent(op4)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, -1, -1));
        
        nextbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nextbutton.setText("NEXT");
        nextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(nextbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 386, 132, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 386, 128, -1));
         jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\OnlinQuizSystem\\onlinequizsystem_pic\\teahub.io-gradient-wallpaper-hd-2761677.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));
        
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void nextbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
       //loadQuestions(2);
       if(queno<size-1)
       {
           jButton2.setEnabled(false);
       }
       else
       {
           jButton2.setEnabled(true);
       }
       if(queno==size)
       {
          JOptionPane.showMessageDialog(this,"Submit to save the answers");
       }
        try {
            answerCheck();
        } catch (Exception ex) {
            System.out.println();
        }
        queno++;
        try {
            sample(Integer.toString(queno));
        } catch (Exception ex) {
            System.out.println();
            
        }
       
        
    }                                          

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            // TODO add your handling code here:
             new MainClient().markSender(mark);
            
        } catch (Exception ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
       dispose();
       
    }                                        

    /**
     * @param args the command line arguments
     */
    public  void display() {
        
        System.out.println("display");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
                try {
                    new Client().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextbutton;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op4;
    private javax.swing.JLabel qno;
    private javax.swing.JLabel questiontxt;
    // End of variables declaration                   
}
